# Generated by Django 3.1.4 on 2021-01-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('Fees', models.CharField(max_length=10)),
                ('from_day', models.CharField(max_length=100)),
                ('to_day', models.CharField(max_length=100)),
                ('from_time', models.CharField(max_length=10)),
                ('to_time', models.CharField(max_length=10)),
            ],
        ),
    ]
