# Generated by Django 3.1.4 on 2021-01-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_auto_20210108_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelation', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_clinic',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_homevisit',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_online',
        ),
    ]
