# Generated by Django 3.1.4 on 2021-01-09 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_appointment_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='S',
            field=models.ForeignKey(default='zero', on_delete=django.db.models.deletion.CASCADE, to='Services.service'),
        ),
    ]
