# Generated by Django 3.1.4 on 2021-01-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_auto_20210109_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='from_time',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='to_time',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
