# Generated by Django 3.1.4 on 2021-01-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_auto_20210109_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='S',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.service'),
        ),
    ]
