# Generated by Django 3.1.4 on 2021-01-12 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='username',
        ),
    ]
