# Generated by Django 3.1.4 on 2021-01-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_account', '0002_auto_20210113_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
